# Makefile.in generated by automake 1.11.1 from Makefile.am.
# chord/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/i3
pkgincludedir = $(includedir)/i3
pkglibdir = $(libdir)/i3
pkglibexecdir = $(libexecdir)/i3
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
noinst_PROGRAMS = gen_conf$(EXEEXT) gen_conf_same$(EXEEXT) \
	test$(EXEEXT) chord_getfingers$(EXEEXT) \
	chord_traceroute$(EXEEXT)
subdir = chord
DIST_COMMON = README $(noinst_HEADERS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
LIBRARIES = $(noinst_LIBRARIES)
ARFLAGS = cru
libchord_a_AR = $(AR) $(ARFLAGS)
libchord_a_LIBADD =
am__objects_1 = gen_utils.$(OBJEXT)
am_libchord_a_OBJECTS = api.$(OBJEXT) eprintf.$(OBJEXT) \
	hosts.$(OBJEXT) pack.$(OBJEXT) sendpkt.$(OBJEXT) \
	chord.$(OBJEXT) finger.$(OBJEXT) join.$(OBJEXT) \
	process.$(OBJEXT) stabilize.$(OBJEXT) util.$(OBJEXT) \
	$(am__objects_1)
libchord_a_OBJECTS = $(am_libchord_a_OBJECTS)
PROGRAMS = $(noinst_PROGRAMS)
am__objects_2 = api.$(OBJEXT) eprintf.$(OBJEXT) hosts.$(OBJEXT) \
	pack.$(OBJEXT) sendpkt.$(OBJEXT) chord.$(OBJEXT) \
	finger.$(OBJEXT) join.$(OBJEXT) process.$(OBJEXT) \
	stabilize.$(OBJEXT) util.$(OBJEXT) $(am__objects_1)
am_chord_getfingers_OBJECTS = chord_getfingers.$(OBJEXT) \
	$(am__objects_2)
chord_getfingers_OBJECTS = $(am_chord_getfingers_OBJECTS)
chord_getfingers_DEPENDENCIES =
am_chord_traceroute_OBJECTS = chord_traceroute.$(OBJEXT) \
	$(am__objects_2)
chord_traceroute_OBJECTS = $(am_chord_traceroute_OBJECTS)
chord_traceroute_DEPENDENCIES =
am_gen_conf_OBJECTS = gen_conf.$(OBJEXT)
gen_conf_OBJECTS = $(am_gen_conf_OBJECTS)
gen_conf_DEPENDENCIES = $(APP_LDADD)
am_gen_conf_same_OBJECTS = gen_conf_same.$(OBJEXT)
gen_conf_same_OBJECTS = $(am_gen_conf_same_OBJECTS)
gen_conf_same_DEPENDENCIES = $(APP_LDADD)
am_test_OBJECTS = test.$(OBJEXT)
test_OBJECTS = $(am_test_OBJECTS)
test_DEPENDENCIES = $(APP_LDADD)
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libchord_a_SOURCES) $(chord_getfingers_SOURCES) \
	$(chord_traceroute_SOURCES) $(gen_conf_SOURCES) \
	$(gen_conf_same_SOURCES) $(test_SOURCES)
DIST_SOURCES = $(libchord_a_SOURCES) $(chord_getfingers_SOURCES) \
	$(chord_traceroute_SOURCES) $(gen_conf_SOURCES) \
	$(gen_conf_same_SOURCES) $(test_SOURCES)
HEADERS = $(noinst_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /usr/local/i3_0_3/i3/missing --run aclocal-1.11
AMTAR = ${SHELL} /usr/local/i3_0_3/i3/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /usr/local/i3_0_3/i3/missing --run autoconf
AUTOHEADER = ${SHELL} /usr/local/i3_0_3/i3/missing --run autoheader
AUTOMAKE = ${SHELL} /usr/local/i3_0_3/i3/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -ggdb -O2 -I/usr/include/libxml2
CPP = gcc -E
CPPFLAGS = -I/usr/include/kerberos -I/usr/kerberos/include  -I/usr/include/libxml2
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ETAGS_ARGS = -C /dev/null
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS =  -lxml2
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /usr/local/i3_0_3/i3/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = i3
PACKAGE_BUGREPORT = 
PACKAGE_NAME = 
PACKAGE_STRING = 
PACKAGE_TARNAME = 
PACKAGE_URL = 
PACKAGE_VERSION = 
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.2
XML2_CONFIG = /usr/bin/xml2-config
XML_CPPFLAGS = -I/usr/include/libxml2
XML_LIBS = -lxml2
abs_builddir = /usr/local/i3_0_3/i3/chord
abs_srcdir = /usr/local/i3_0_3/i3/chord
abs_top_builddir = /usr/local/i3_0_3/i3
abs_top_srcdir = /usr/local/i3_0_3/i3
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /usr/local/i3_0_3/i3/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
lt_ECHO = echo
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..

# chord compilation
noinst_LIBRARIES = libchord.a
noinst_HEADERS = chord_api.h  chord.h  debug.h  eprintf.h
utils_SOURCES = ../utils/gen_utils.c
libchord_a_SOURCES = api.c  eprintf.c  hosts.c  pack.c  sendpkt.c \
		     chord.c  finger.c  join.c  process.c  stabilize.c \
		     util.c $(utils_SOURCES) 

APP_LDADD = libchord.a
gen_conf_SOURCES = gen_conf.c
gen_conf_LDADD = $(APP_LDADD)
gen_conf_same_SOURCES = gen_conf_same.c
gen_conf_same_LDADD = $(APP_LDADD)
test_SOURCES = test.c
test_LDADD = $(APP_LDADD)
chord_getfingers_SOURCES = chord_getfingers.c ${libchord_a_SOURCES}
chord_getfingers_LDADD = $(APP_LADD)
chord_traceroute_SOURCES = chord_traceroute.c ${libchord_a_SOURCES}
chord_traceroute_LDADD = $(APP_LADD)
SIM_DIR = sim
EXTRA_DIST = $(SIM_DIR)/def.h $(SIM_DIR)/event.h $(SIM_DIR)/in.c \
	     $(SIM_DIR)/server.c $(SIM_DIR)/sim_util.c \
	     $(SIM_DIR)/traffic_gen.c $(SIM_DIR)/var.h $(SIM_DIR)/event.c \
	     $(SIM_DIR)/fun.h $(SIM_DIR)/incl.h $(SIM_DIR)/sim.c \
	     $(SIM_DIR)/sim_util.h $(SIM_DIR)/traffic_gen.h \
	     $(SIM_DIR)/Makefile $(SIM_DIR)/README \
	     $(SIM_DIR)/examples/ex1.sc $(SIM_DIR)/examples/ex2.sc \
	     $(SIM_DIR)/examples/ex3.sc $(SIM_DIR)/examples/simple.sc

CLEANFILES = core *.core *~
MAINTAINERCLEANFILES = Makefile.in
all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu chord/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu chord/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
libchord.a: $(libchord_a_OBJECTS) $(libchord_a_DEPENDENCIES) 
	-rm -f libchord.a
	$(libchord_a_AR) libchord.a $(libchord_a_OBJECTS) $(libchord_a_LIBADD)
	$(RANLIB) libchord.a

clean-noinstPROGRAMS:
	@list='$(noinst_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
chord_getfingers$(EXEEXT): $(chord_getfingers_OBJECTS) $(chord_getfingers_DEPENDENCIES) 
	@rm -f chord_getfingers$(EXEEXT)
	$(LINK) $(chord_getfingers_OBJECTS) $(chord_getfingers_LDADD) $(LIBS)
chord_traceroute$(EXEEXT): $(chord_traceroute_OBJECTS) $(chord_traceroute_DEPENDENCIES) 
	@rm -f chord_traceroute$(EXEEXT)
	$(LINK) $(chord_traceroute_OBJECTS) $(chord_traceroute_LDADD) $(LIBS)
gen_conf$(EXEEXT): $(gen_conf_OBJECTS) $(gen_conf_DEPENDENCIES) 
	@rm -f gen_conf$(EXEEXT)
	$(LINK) $(gen_conf_OBJECTS) $(gen_conf_LDADD) $(LIBS)
gen_conf_same$(EXEEXT): $(gen_conf_same_OBJECTS) $(gen_conf_same_DEPENDENCIES) 
	@rm -f gen_conf_same$(EXEEXT)
	$(LINK) $(gen_conf_same_OBJECTS) $(gen_conf_same_LDADD) $(LIBS)
test$(EXEEXT): $(test_OBJECTS) $(test_DEPENDENCIES) 
	@rm -f test$(EXEEXT)
	$(LINK) $(test_OBJECTS) $(test_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/api.Po
include ./$(DEPDIR)/chord.Po
include ./$(DEPDIR)/chord_getfingers.Po
include ./$(DEPDIR)/chord_traceroute.Po
include ./$(DEPDIR)/eprintf.Po
include ./$(DEPDIR)/finger.Po
include ./$(DEPDIR)/gen_conf.Po
include ./$(DEPDIR)/gen_conf_same.Po
include ./$(DEPDIR)/gen_utils.Po
include ./$(DEPDIR)/hosts.Po
include ./$(DEPDIR)/join.Po
include ./$(DEPDIR)/pack.Po
include ./$(DEPDIR)/process.Po
include ./$(DEPDIR)/sendpkt.Po
include ./$(DEPDIR)/stabilize.Po
include ./$(DEPDIR)/test.Po
include ./$(DEPDIR)/util.Po

.c.o:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

.c.lo:
	$(LTCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(LTCOMPILE) -c -o $@ $<

gen_utils.o: ../utils/gen_utils.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gen_utils.o -MD -MP -MF $(DEPDIR)/gen_utils.Tpo -c -o gen_utils.o `test -f '../utils/gen_utils.c' || echo '$(srcdir)/'`../utils/gen_utils.c
	$(am__mv) $(DEPDIR)/gen_utils.Tpo $(DEPDIR)/gen_utils.Po
#	source='../utils/gen_utils.c' object='gen_utils.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gen_utils.o `test -f '../utils/gen_utils.c' || echo '$(srcdir)/'`../utils/gen_utils.c

gen_utils.obj: ../utils/gen_utils.c
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT gen_utils.obj -MD -MP -MF $(DEPDIR)/gen_utils.Tpo -c -o gen_utils.obj `if test -f '../utils/gen_utils.c'; then $(CYGPATH_W) '../utils/gen_utils.c'; else $(CYGPATH_W) '$(srcdir)/../utils/gen_utils.c'; fi`
	$(am__mv) $(DEPDIR)/gen_utils.Tpo $(DEPDIR)/gen_utils.Po
#	source='../utils/gen_utils.c' object='gen_utils.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o gen_utils.obj `if test -f '../utils/gen_utils.c'; then $(CYGPATH_W) '../utils/gen_utils.c'; else $(CYGPATH_W) '$(srcdir)/../utils/gen_utils.c'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LIBRARIES) $(PROGRAMS) $(HEADERS)
installdirs:
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-am

clean-am: clean-generic clean-libtool clean-noinstLIBRARIES \
	clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am:

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am check check-am clean clean-generic \
	clean-libtool clean-noinstLIBRARIES clean-noinstPROGRAMS ctags \
	distclean distclean-compile distclean-generic \
	distclean-libtool distclean-tags distdir dvi dvi-am html \
	html-am info info-am install install-am install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am

$(PROGRAMS): $(LDEPS)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
