/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "file_client/d_messages.pb-c.h"
void   client_request__init
                     (ClientRequest         *message)
{
  static ClientRequest init_value = CLIENT_REQUEST__INIT;
  *message = init_value;
}
size_t client_request__get_packed_size
                     (const ClientRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_request__pack
                     (const ClientRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_request__pack_to_buffer
                     (const ClientRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientRequest *
       client_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientRequest *)
     protobuf_c_message_unpack (&client_request__descriptor,
                                allocator, len, data);
}
void   client_request__free_unpacked
                     (ClientRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   client_request_reply__init
                     (ClientRequestReply         *message)
{
  static ClientRequestReply init_value = CLIENT_REQUEST_REPLY__INIT;
  *message = init_value;
}
size_t client_request_reply__get_packed_size
                     (const ClientRequestReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client_request_reply__pack
                     (const ClientRequestReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client_request_reply__pack_to_buffer
                     (const ClientRequestReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ClientRequestReply *
       client_request_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ClientRequestReply *)
     protobuf_c_message_unpack (&client_request_reply__descriptor,
                                allocator, len, data);
}
void   client_request_reply__free_unpacked
                     (ClientRequestReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &client_request_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query__init
                     (Query         *message)
{
  static Query init_value = QUERY__INIT;
  *message = init_value;
}
size_t query__get_packed_size
                     (const Query *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query__pack
                     (const Query *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query__pack_to_buffer
                     (const Query *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Query *
       query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Query *)
     protobuf_c_message_unpack (&query__descriptor,
                                allocator, len, data);
}
void   query__free_unpacked
                     (Query *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_reply_success__init
                     (QueryReplySuccess         *message)
{
  static QueryReplySuccess init_value = QUERY_REPLY_SUCCESS__INIT;
  *message = init_value;
}
size_t query_reply_success__get_packed_size
                     (const QueryReplySuccess *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_success__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_reply_success__pack
                     (const QueryReplySuccess *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_success__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_reply_success__pack_to_buffer
                     (const QueryReplySuccess *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_success__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryReplySuccess *
       query_reply_success__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryReplySuccess *)
     protobuf_c_message_unpack (&query_reply_success__descriptor,
                                allocator, len, data);
}
void   query_reply_success__free_unpacked
                     (QueryReplySuccess *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_success__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   query_reply_failure__init
                     (QueryReplyFailure         *message)
{
  static QueryReplyFailure init_value = QUERY_REPLY_FAILURE__INIT;
  *message = init_value;
}
size_t query_reply_failure__get_packed_size
                     (const QueryReplyFailure *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_failure__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t query_reply_failure__pack
                     (const QueryReplyFailure *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_failure__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t query_reply_failure__pack_to_buffer
                     (const QueryReplyFailure *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_failure__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
QueryReplyFailure *
       query_reply_failure__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (QueryReplyFailure *)
     protobuf_c_message_unpack (&query_reply_failure__descriptor,
                                allocator, len, data);
}
void   query_reply_failure__free_unpacked
                     (QueryReplyFailure *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &query_reply_failure__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   push__init
                     (Push         *message)
{
  static Push init_value = PUSH__INIT;
  *message = init_value;
}
size_t push__get_packed_size
                     (const Push *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t push__pack
                     (const Push *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t push__pack_to_buffer
                     (const Push *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Push *
       push__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Push *)
     protobuf_c_message_unpack (&push__descriptor,
                                allocator, len, data);
}
void   push__free_unpacked
                     (Push *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   push_reply__init
                     (PushReply         *message)
{
  static PushReply init_value = PUSH_REPLY__INIT;
  *message = init_value;
}
size_t push_reply__get_packed_size
                     (const PushReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t push_reply__pack
                     (const PushReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t push_reply__pack_to_buffer
                     (const PushReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PushReply *
       push_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PushReply *)
     protobuf_c_message_unpack (&push_reply__descriptor,
                                allocator, len, data);
}
void   push_reply__free_unpacked
                     (PushReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &push_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client_request__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ClientRequest, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange client_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ClientRequest",
  "ClientRequest",
  "ClientRequest",
  "",
  sizeof(ClientRequest),
  1,
  client_request__field_descriptors,
  client_request__field_indices_by_name,
  1,  client_request__number_ranges,
  (ProtobufCMessageInit) client_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor client_request_reply__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ClientRequestReply, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ClientRequestReply, code),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client_request_reply__field_indices_by_name[] = {
  1,   /* field[1] = code */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange client_request_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor client_request_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ClientRequestReply",
  "ClientRequestReply",
  "ClientRequestReply",
  "",
  sizeof(ClientRequestReply),
  2,
  client_request_reply__field_descriptors,
  client_request_reply__field_indices_by_name,
  1,  client_request_reply__number_ranges,
  (ProtobufCMessageInit) client_request_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query__field_descriptors[3] =
{
  {
    "reply_addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, reply_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reply_port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, reply_port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Query, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query__field_indices_by_name[] = {
  2,   /* field[2] = name */
  0,   /* field[0] = reply_addr */
  1,   /* field[1] = reply_port */
};
static const ProtobufCIntRange query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor query__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Query",
  "Query",
  "Query",
  "",
  sizeof(Query),
  3,
  query__field_descriptors,
  query__field_indices_by_name,
  1,  query__number_ranges,
  (ProtobufCMessageInit) query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_reply_success__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QueryReplySuccess, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_reply_success__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange query_reply_success__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor query_reply_success__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "QueryReplySuccess",
  "QueryReplySuccess",
  "QueryReplySuccess",
  "",
  sizeof(QueryReplySuccess),
  1,
  query_reply_success__field_descriptors,
  query_reply_success__field_indices_by_name,
  1,  query_reply_success__number_ranges,
  (ProtobufCMessageInit) query_reply_success__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor query_reply_failure__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(QueryReplyFailure, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned query_reply_failure__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange query_reply_failure__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor query_reply_failure__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "QueryReplyFailure",
  "QueryReplyFailure",
  "QueryReplyFailure",
  "",
  sizeof(QueryReplyFailure),
  1,
  query_reply_failure__field_descriptors,
  query_reply_failure__field_indices_by_name,
  1,  query_reply_failure__number_ranges,
  (ProtobufCMessageInit) query_reply_failure__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor push__field_descriptors[3] =
{
  {
    "reply_addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Push, reply_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reply_port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Push, reply_port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Push, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned push__field_indices_by_name[] = {
  2,   /* field[2] = name */
  0,   /* field[0] = reply_addr */
  1,   /* field[1] = reply_port */
};
static const ProtobufCIntRange push__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor push__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Push",
  "Push",
  "Push",
  "",
  sizeof(Push),
  3,
  push__field_descriptors,
  push__field_indices_by_name,
  1,  push__number_ranges,
  (ProtobufCMessageInit) push__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor push_reply__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PushReply, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned push_reply__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange push_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor push_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PushReply",
  "PushReply",
  "PushReply",
  "",
  sizeof(PushReply),
  1,
  push_reply__field_descriptors,
  push_reply__field_indices_by_name,
  1,  push_reply__number_ranges,
  (ProtobufCMessageInit) push_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
